title:              Md Arifuzzaman Faisal 
email:              faisal.buet.eee@gmail.com
description:        Nano Physics - Electromagnetics - Data Science - Artificial Intelligence 
author:             Md Arifuzzaman Faisal 
baseurl:            ""
url:                "https://arifuzzamanfaisal.github.io"

# Social Profiles
twitter_username:   arifuzzamanfaisal
github_username:    arifuzzamanfaisal
facebook_username:  arifuzzamanfaisal
instagram_username:  arifuzzamanfaisal
linkedin_username: arifuzzamanfaisal

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
