title:              Md Arifuzzaman Faisal 
logo:               Arifuzzaman Faisal
site_title:         Welcome ! 
email:              faisal.buet.eee@gmail.com
description:        NanoElectronics - Plasmas - Artificial Intelligence 
author:             Md Arifuzzaman Faisal 
baseurl:            ""
url:                "https://arifuzzamanfaisal.github.io"

# Social Profiles
twitter_username:   eee_faisal
github_username:    arifuzzamanfaisal
facebook_username:  
instagram_username:  
linkedin_username: arifuzzamanfaisal

# Add your google-analytics ID here to activate google analytics
google_analytics:   G-2X97T3PWEX #UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

theme: jekyll-theme-cayman